### ISSUE TITLE
Why doesn't array_view provide non-const iterators?

### ISSUE THREAD

**Issue by jakub-trzebiatowski** [rhysd/array_view#1]

**Comment by rhysd** [comment]
Because I didn't need it.  PR is welcome.

**Comment by rhysd** [comment]
@cubuspl42 

FYI, please refer the interface of `array_view` suggested for C++17.

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3851.pdf

The iterator (`bounds_iterator`) is always const iterator.

**Comment by jakub-trzebiatowski** [comment]
I was curious if there is any motivation for this. I'm thinking about an alternative for C-style `void f(int *out_array, int n);` which is cool because it doesn't care if your array is `std::vector::data()`, `std::array::data()`, or pure array.

**Comment by rhysd** [comment]
@cubuspl42 

I agree.

And the C-style interface often comes with `const` like `void f(const int* data, const int len)` to protect readonly data.  `array_view` also provides the readonly interface.
